import type { NextPage } from 'next'
import Hero from './Hero'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>dine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./public/images/favicon.png" />
      </Head>

      <main>
        <Hero />

        <h3 className='text-4xl'>Enjoyable place for all the family</h3>
        <p className='text-sm'>Our relaxed surroundings make dining with us a great experience for everyone. We can even arrange 
  a tour of the farm before your meal.</p>

        <h3 className='text-4xl'>The most locally sourced food</h3>
        <p className='text-sm'>All our ingredients come directly from our farm or local fishery. So you can be sure that you’re 
  eating the freshest, most sustainable food.</p>

        <h3 className='text-4xl'>A few highlights from our menu</h3>
        <p className='text-sm'>We cater for all dietary requirements, but here’s a glimpse at some of our diner’s favourites. 
  Our menu is revamped every season.</p>

        <h3 className='text-4xl'>Seared Salmon Fillet</h3>
        <p className='text-sm'>Our locally sourced salmon served with a refreshing buckwheat summer salad.</p>

        <h3 className='text-4xl'>Rosemary Filet Mignon</h3>
        <p className='text-sm'>Our prime beef served to your taste with a delicious choice of seasonal sides.</p>

        <h3 className='text-4xl'>Summer Fruit Chocolate Mousse</h3>
        <p className='text-sm'>Creamy mousse combined with summer fruits and dark chocolate shavings.</p>


        <p>Family Gathering</p>
        <p>Special Events</p>
        <p>Social Events</p>

        <h3 className='text-4xl'>Family Gathering</h3>
        <p className='text-sm'>We love catering for entire families. So please bring everyone along for a special meal with your 
  loved ones. We’ll provide a memorable experience for all.</p>

        <h3 className='text-4xl'>Special Events</h3>
        <p className='text-sm'>Whether it’s a romantic dinner or special date you’re celebrating with others we’ll look after you. 
  We’ll be sure to mark your special date with an unforgettable meal.</p>

        <h3 className='text-4xl'>Social Events</h3>
        <p className='text-sm'>Are you looking to have a larger social event? No problem! We’re more than happy to cater for big 
  parties. We’ll work with you to make your event a hit with everyone.</p>


        <h3 className='text-4xl'>Ready to make a reservation?</h3>
        <button className='text-xs'>BOOK A TABLE</button>
      </main>

      <footer className=''>
        <h1>dine</h1>
        <p>Marthwaite, Sedbergh
          Cumbria
          +00 44 123 4567
        </p>
        <p> Open Times
        Mon - Fri: 09:00 AM - 10:00 PM
        Sat - Sun: 09:00 AM - 11:30 PM</p>
  
      </footer>
    </div>
  )
}

export default Home
