import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>dine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./public/images/favicon.png" />
      </Head>

      <main className={styles.main}>
        <h1>dine</h1>
        <h2>Exquisite dining since 1989</h2>
        <p> Experience our seasonal menu in beautiful country surroundings. Eat the freshest produce from the comfort of our farmhouse.</p>
        <button>Book a table</button>

        <h2>Enjoyable place for all the family</h2>
        <p>Our relaxed surroundings make dining with us a great experience for everyone. We can even arrange 
  a tour of the farm before your meal.</p>

        <h2>The most locally sourced food</h2>
        <p>All our ingredients come directly from our farm or local fishery. So you can be sure that you’re 
  eating the freshest, most sustainable food.</p>

        <h2>A few highlights from our menu</h2>
        <p>We cater for all dietary requirements, but here’s a glimpse at some of our diner’s favourites. 
  Our menu is revamped every season.</p>

        <h3>Seared Salmon Fillet</h3>
        <p>Our locally sourced salmon served with a refreshing buckwheat summer salad.</p>

        <h3>Rosemary Filet Mignon</h3>
        <p>Our prime beef served to your taste with a delicious choice of seasonal sides.</p>

        <h3>Summer Fruit Chocolate Mousse</h3>
        <p>Creamy mousse combined with summer fruits and dark chocolate shavings.</p>


        <p>Family Gathering</p>
        <p>Special Events</p>
        <p>Social Events</p>

        <h2>Family Gathering</h2>
        <p>We love catering for entire families. So please bring everyone along for a special meal with your 
  loved ones. We’ll provide a memorable experience for all.</p>

        <h2>Special Events</h2>
        <p>Whether it’s a romantic dinner or special date you’re celebrating with others we’ll look after you. 
  We’ll be sure to mark your special date with an unforgettable meal.</p>

        <h2>Social Events</h2>
        <p>Are you looking to have a larger social event? No problem! We’re more than happy to cater for big 
  parties. We’ll work with you to make your event a hit with everyone.</p>


        <h2>Ready to make a reservation?</h2>
        <button>BOOK A TABLE</button>
      </main>

      <footer className={styles.footer}>
        <h1>dine</h1>
        <p>Marthwaite, Sedbergh
          Cumbria
          +00 44 123 4567
        </p>
        <p> Open Times
        Mon - Fri: 09:00 AM - 10:00 PM
        Sat - Sun: 09:00 AM - 11:30 PM</p>
  
      </footer>
    </div>
  )
}

export default Home
